### ISSUE TITLE
Display broken in qutebrowser

### ISSUE THREAD

**Issue by VincentTam** [donaldboulton/DWB#75] opened 2019-05-19 10:31 UTC
# Bugs

**Footer display raw JS code in qutebrowser**

**To Reproduce**

1. Go to 'https://donboulton.com/2018-02-26-post-staticman-with-gitlab'
3. Scroll down to bottom

**Screenshots**

![web site display error](http://imgur.com/0R3z3sOl.png)
Image link: http://imgur.com/0R3z3sOl.png

**Desktop (please complete the following information):**
 - OS: [e.g. Xubuntu 18.04 LTS]
 - Browser [e.g. qutebrowser]
 - Version [e.g. v1.1.1]

**Comment by donaldboulton** [comment] 2019-05-19 12:24
Thanks I check it out.

**Comment by donaldboulton** [comment] 2019-05-19 13:01
I downloaded and installed qutebrowser and viewed my home page and saw the issue you described. Then I went to My [Staticman Gitlab post](https://donboulton.com/2018-02-26-post-staticman-with-gitlab) and it was fine. I will try preloading the script! 

Thanks for the Comments
Donald Boulton

**Comment by donaldboulton** [comment] 2019-05-19 14:24
Updated jquery and cookiebar & preloaded cookiebar script, I do not see the bug anymore. I am using a Windows machine. If anyone gets time check out this issue on a OS: [e.g. Xubuntu 18.04 LTS] machine or a Apple OS and let me know if you still see the issue.
Closing for now

**Comment by VincentTam** [comment] 2019-05-19 16:50
I'm using the same OS, and I'm still seeing this after doing the same thing:

![screenshot error](http://imgur.com/EWFiU4Rl.png)  
Image URL: http://imgur.com/EWFiU4Rl.png

**Comment by donaldboulton** [comment] 2019-05-19 21:29
Cannot reproduce, caching issue maybe, tried :restart which clears cache for page is there a way to clear cache in qutebrowser on a network tab could not find it.

**Comment by donaldboulton** [comment] 2019-05-19 21:39
Just got the error on MS Edge on home page disappeared on next page load.
Going with npm module not cdn for loading cookiebar had similar sw.js caching issue with my Gatsby site with cookie-consent / cookiebar from a CDN at publiuslogic.com so I will fix it going npm and include it in my webpack build for react components and not bundled with jekyll like I have it now.
Thanks
Donald Boulton

**Comment by VincentTam** [comment] 2019-05-21 10:42
Thanks for fixing it.  It now looks good on Xubuntu 18.04 qutebrowser.

**Closed as completed** 2019-07-01 21:04 UTC
Labels: bug
